### ISSUE TITLE
Update on pipeline and feature issues

### ISSUE THREAD

**Issue by Derek-Hardy** [0WN463/NLP-Issue-Labeller#7]
**Tasks:**

- [ ] HTTP links (maybe image link as well) are not yet replaced from “text”, which might affect word embedding.
- [ ] Indicative word count (bug, feature, doc) can be added into feature vector. [here](https://github.com/0WN463/CS4248-Project/issues/4#issue-825903497)
- [ ] Do some selections on the feature vector, remove irrelevant ones that adversely impact accuracy.
- [ ] `dataframe_generator` might want to incorporate `xxx_links_extracted.json`
- [ ] Update `code_count`, `link_count` and `image_count` method in `handcrafted_feature_extractor.py` (links and code blocks can get directly from JSON data, consider remove image feature)

Model-wise, maybe `SGDClassifier` can be tried as well.
